# Generated by Django 5.2.7 on 2025-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=15)),
            ],
        ),
    ]
